version: '3.8'

services:
  nestjs_api:
    container_name: nestjs_api
    hostname: nestjs_api
    image: nestjs-api:1.0.0
    environment:
      - NODE_ENV:${NODE_ENV}
      - DATABASE_URL:${DATABASE_URL}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    command: npm run start:debug
    env_file:
      - .env
    ports:
      - "9000:9000"
    networks:
      - nestjs-network
    #volumes:
    #  - .:/app
    #  - ./app/node_modules
    #volumes:
    #  - ./:/app
    #  - /app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbitmq


  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - nestjs-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - nestjs-network

  rabbitmq:
    build: ./rabbitmq
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
      - nestjs-network

volumes:
  rabbitmq_data:
  rabbitmq_log:
  db:
    driver: local

networks:
  nestjs-network:
    name: nestjs-network
    driver: bridge
